### PR TITLE
fix equation numbering in mathjax configuration

### PR DESCRIPTION
**Pull request by hoxca**
I'm the only one who use equation numbering in mathjax i guess ;)

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
It seems to be a rare usecase but I added this feature too. I've merged your commit in 51fb45c9e1d38892ba3329d905b31e4f924ac159.

**Comment by digitalcraftsman** [comment]
Hello @hoxca,

due to some rendering issues (see #8) I needed to remove your changes and updated the MathJax configs (see 4cff4bc24f58f70313918635c6f1f1ce4a93059c).

The main problem was that footnotes, inline-code and code-blocks were not rendered correctly. I don't now which requirements you've for the equation format. 

For inline-equations you could use

```
$\omega = d\phi / dt$
```

and for larger blocks of math try

```
$$I = \int \rho R^{2} dV$$
```

The difference is just the use of one or two `$`.

Otherwise, if you want to give it another try please check your changes with [this example post](https://gist.github.com/digitalcraftsman/8d20969072c680602fa4).

**Comment by hoxca** [comment]
Equation numbering is used with display math

As you can see it there:
http://cdn.mathjax.org/mathjax/latest/test/sample-eqnum.html

**Comment by digitalcraftsman** [comment]
Thanks for the reference. Hopefully I can unify both configurations.

**Pull request closed without merging**
