### PR TITLE
Added option to omit date line from individual pages

### PR DESCRIPTION
**Pull request by gregasmaximus**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @gregasmaximus,
 
thanks for submitting this enhancements :+1:

**Comment by gregasmaximus** [comment]
I realize that by mistake, I included the "disable MathJax" in this merge -- it was meant to be a separate merge. I have a small update for that, so I will submit another merge request shortly.
The problem is that if an existing user pulls the theme and they don't have mathjax = true in their config.toml, it will turn off mathjax, breaking their equations.

In the upcoming merge, I am inverting the logic. You must set disable_mathjax = true to disable it. If the param disable_mathjax does not exist, it will not be disabled. So nothing will break.

Sorry about including this before it was ready...I did not mean to include that in the merge, only the nodateline feature.

**Comment by digitalcraftsman** [comment]
You're right. This change would indeed be not backwards-compatible.

**Comment by gregasmaximus** [comment]
It's fixed in my latest pull request so that it's now backwards compatible.

**Pull request merged**
